name: tts_client
description: Durt package to simplify the interaction with flutter_tts.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^3.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.4.0
