name: shared_preferences_storage
description: Durt package to simplify the interaction with shared_preferences.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.4.0
